# Generated by Django 5.0.6 on 2025-04-23 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='grupo_sanguineo',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('No sabe', 'No sabe')], default='O+', max_length=15),
        ),
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergia_alimentos', models.BooleanField(default=False)),
                ('alergia_alimentos_detalle', models.TextField(blank=True, null=True)),
                ('alergia_medicamentos', models.BooleanField(default=False)),
                ('alergia_medicamentos_detalle', models.TextField(blank=True, null=True)),
                ('alergia_otros', models.BooleanField(default=False)),
                ('alergia_otros_detalle', models.TextField(blank=True, null=True)),
                ('cancer', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('vih', models.BooleanField(default=False)),
                ('tabaquismo', models.BooleanField(default=False)),
                ('tabaquismo_detalle', models.TextField(blank=True, null=True)),
                ('alcoholismo', models.BooleanField(default=False)),
                ('alcoholismo_detalle', models.TextField(blank=True, null=True)),
                ('dieta_alta_azucares', models.BooleanField(default=False)),
                ('cepillado', models.BooleanField(default=False)),
                ('hilo_dental', models.BooleanField(default=False)),
                ('enjuague', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Principal.paciente')),
            ],
        ),
    ]
