# Generated by Django 5.0.6 on 2025-03-26 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requiere_pagos_parciales', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Completada', 'Completada')], default='Pendiente', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('notas', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='TratamientoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.historiaclinica')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='PagoTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=20)),
                ('tratamiento_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.tratamientopaciente')),
            ],
        ),
    ]
