# Generated by Django 5.0.6 on 2025-04-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_tratamiento_cita_historiaclinica_tratamientopaciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
