# Generated by Django 5.0.6 on 2025-04-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_alter_paciente_grupo_sanguineo_antecedentes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antecedentes',
            old_name='cancer',
            new_name='asma',
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='enfermedad_cardiaca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='hemorragias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='hipertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='otras_enfermedades',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='otras_enfermedades_detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='tuberculosis',
            field=models.BooleanField(default=False),
        ),
    ]
