# Generated by Django 5.0.6 on 2025-04-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0003_cita_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='discapacidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='grupo_sanguineo',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3),
        ),
        migrations.AddField(
            model_name='paciente',
            name='orientacion_sexual',
            field=models.CharField(blank=True, choices=[('Heterosexual', 'Heterosexual'), ('Homosexual', 'Homosexual'), ('Bisexual', 'Bisexual'), ('Otro', 'Otro')], default='Otro', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Sin especificar', 'Sin especificar')], default='Sin especificar', max_length=20),
        ),
    ]
