# Generated by Django 5.0.6 on 2025-04-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0003_rename_cancer_antecedentes_asma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentes',
            name='enfermedad_cardiaca_detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='hemorragias_detalle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
