# Generated by Django 5.0.6 on 2025-05-06 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0005_motivoconsulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenEstomatognatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('examen_sin_patologia', models.BooleanField(default=False)),
                ('regiones', models.JSONField(default=dict)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.paciente')),
            ],
        ),
    ]
